---
title: "Pertemuan 2 - Justin Julio CT M0401241064"
output: html_document
date: "2026-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
data <- read.csv("C:\\Users\\yuuen\\OneDrive\\Documents\\Kuliah\\IPB\\Semester 4\\Anreg\\WineQuality.csv")
head(data)

```

```{r}
data <- data[, c("quality", "alcohol")]
colnames(data) <- c("Y", "X1")
```

```{r}
n <- nrow(data)
```

```{r}
plot(data$X1, data$Y,
     main = "Alcohol vs Wine Quality",
     xlab = "Alcohol",
     ylab = "Wine Quality")

```
```{r}
summary(data$Y)
boxplot(data$Y)
```

```{r}
summary(data$X1)
boxplot(data$X1)
```

# Pembentukan Model

## Koefisien Regresi

```{r}
x <- data$X1
y <- data$Y
```

```{r}
b1 <- (sum(x*y)-sum(x)*sum(y)/n)/(sum(x^2)-(sum(x)^2/n))
b0 <- mean(y)-b1*mean(x)

cat("Koefisien b0:", b0, "\n")  
cat("Koefisien b1:", b1, "\n")
```

## Standar Error Parameter Regresi

```{r}
galat <- y-(b0+b1*x)
ragam_galat <- sum(galat^2)/(n-2)

se_b0 <- sqrt(ragam_galat*(1/n+mean(x)^2/sum((x-mean(x))^2)))
se_b1 <- sqrt(ragam_galat/sum((x-mean(x))^2))

cat("Standar error b0:", se_b0, "\n") 
cat("Standar error b1:", se_b1, "\n")

```
## Signifikansi Parameter (nilai-t)
```{r}
t_b0 <- b0/se_b0
t_b1 <- b1/se_b1
p_b0 <- 2*pt(-abs(t_b0), df = n-2)
p_b1 <- 2*pt(-abs(t_b1), df = n-2)

cat("Nilai t b0:", t_b0, "p-value:", p_b0, "\n")
cat("Nilai t b1:", t_b1, "p-value:", p_b1, "\n")

```


## Koefisien Determinasi dan Penyesuaiannya

```{r}
r <- (sum(x*y)-sum(x)*sum(y)/n) /
     sqrt((sum(x^2)-(sum(x)^2/n))*(sum(y^2)-(sum(y)^2/n)))

R2 <- r^2
R2

Adj_R2 <- 1 - ((1 - R2)*(n - 1)/(n - 2))
Adj_R2

```

## Signifikansi Simultan (F)
```{r}
JKG <- sum((y - (b0+b1*x))^2)
JKReg <- sum(((b0+b1*x) - mean(y))^2)

Fhit <- (JKReg/1)/(JKG/(n-2))
Fhit

p_Fhit <- 1 - pf(Fhit, 1, n-2)
p_Fhit

```


```{r}
model <- lm(Y ~ X1, data = data)
summary(model)
anova(model)

```


```{r pressure, echo=FALSE}
plot(pressure)
```

